M48
; DRILL file {KiCad 7.0.11-7.0.11~ubuntu22.04.1} date Fri 31 Jan 2025 09:35:23 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-01-31T21:35:23-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11-7.0.11~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1378
%
G90
G05
T1
X4.209Y-5.014
X5.07Y-2.187
M30
